server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: kafka-kopanda
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    connect-timeout: 2000ms
    socket-timeout: 2000ms

  # H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:kopanda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: Asia/Seoul

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: Asia/Seoul

  profiles:
    active: dev

kafka:
  client:
    bootstrap-servers: localhost:29092
    default-timeout-ms: 5000
    request-timeout-ms: 3000
    metadata-max-age-ms: 300000
    reconnect-backoff-ms: 50
    retry-backoff-ms: 100
    max-block-ms: 60000
    buffer-memory: 33554432
    compression-type: none
    batch-size: 16384
    linger-ms: 0
    max-request-size: 1048576
    receive-buffer-bytes: 32768
    send-buffer-bytes: 131072
    max-in-flight-requests-per-connection: 5
    connections-max-idle-ms: 540000
    session-timeout-ms: 30000
    heartbeat-interval-ms: 3000
    max-poll-records: 500
    max-poll-interval-ms: 300000
    auto-offset-reset: earliest
    enable-auto-commit: false
    auto-commit-interval-ms: 5000
    check-crcs: true
    exclude-internal-topics: true
    isolation-level: read_uncommitted
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

  admin:
    request-timeout-ms: 5000
    default-api-timeout-ms: 5000
    operation-timeout-ms: 30000
    fetch-timeout-ms: 5000

  consumer:
    group-id: kopanda-consumer
    auto-offset-reset: earliest
    enable-auto-commit: false
    max-poll-records: 500
    max-poll-interval-ms: 300000
    session-timeout-ms: 30000
    heartbeat-interval-ms: 3000
    fetch-min-bytes: 1
    fetch-max-wait-ms: 500
    fetch-max-bytes: 52428800
    max-partition-fetch-bytes: 1048576
    check-crcs: true
    exclude-internal-topics: true
    isolation-level: read_uncommitted

  producer:
    acks: all
    retries: 2147483647
    batch-size: 16384
    linger-ms: 0
    buffer-memory: 33554432
    compression-type: none
    max-request-size: 1048576
    max-block-ms: 60000
    request-timeout-ms: 30000
    delivery-timeout-ms: 120000
    enable-idempotence: false
    max-in-flight-requests-per-connection: 5
    metadata-max-age-ms: 300000
    reconnect-backoff-ms: 50
    retry-backoff-ms: 100

# 애플리케이션 설정
app:
  connection:
    default-port: 29092  # Docker Kafka 컨테이너 포트
    test-timeout-ms: 5000
    max-connections: 100
    connection-pool-size: 10
    default-host: localhost  # Docker 호스트

  message:
    default-page-size: 20
    max-page-size: 1000
    preview-timeout-ms: 10000
    search-timeout-ms: 30000
    max-message-size: 1048576

  topic:
    default-replication-factor: 1
    default-partitions: 1
    max-partitions: 1000
    max-replication-factor: 10

  monitoring:
    metrics-interval-ms: 30000
    health-check-interval-ms: 60000
    alert-check-interval-ms: 300000

  security:
    cors:
      allowed-origins:
        - "http://localhost:3000"
        - "http://localhost:8080"
        - "http://127.0.0.1:3000"
        - "http://127.0.0.1:8080"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - "*"
      allow-credentials: true
      max-age: 3600

    rate-limit:
      enabled: true
      requests-per-minute: 1000
      burst-capacity: 100

# 로깅 설정
logging:
  level:
    com.sleekydz86.kopanda: DEBUG
    org.apache.kafka: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.redis: WARN
    io.lettuce.core: WARN
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/kafka-kopanda.log
    max-size: 100MB
    max-history: 30

# Spring Boot Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      version: ${project.version}

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.sleekydz86.kopanda: DEBUG
    org.apache.kafka: DEBUG
    org.springframework.web: DEBUG

kafka:
  client:
    default-timeout-ms: 3000
    request-timeout-ms: 2000

app:
  connection:
    test-timeout-ms: 3000
  message:
    preview-timeout-ms: 5000
    search-timeout-ms: 15000

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.sleekydz86.kopanda: INFO
    org.apache.kafka: WARN
    org.springframework.web: WARN
  file:
    max-size: 500MB
    max-history: 90

kafka:
  client:
    default-timeout-ms: 10000
    request-timeout-ms: 5000

app:
  connection:
    test-timeout-ms: 10000
  message:
    preview-timeout-ms: 30000
    search-timeout-ms: 60000
  security:
    cors:
      allowed-origins:
        - "https://your-production-domain.com"
    rate-limit:
      requests-per-minute: 500
      burst-capacity: 50

---
spring:
  config:
    activate:
      on-profile: test

logging:
  level:
    com.sleekydz86.kopanda: DEBUG
    root: INFO

kafka:
  client:
    default-timeout-ms: 1000
    request-timeout-ms: 1000

app:
  connection:
    test-timeout-ms: 1000
  message:
    preview-timeout-ms: 2000
    search-timeout-ms: 5000