server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: kafka-kopanda

  datasource:
    url: jdbc:h2:mem:kopanda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_UPPER=false;INIT=CREATE SCHEMA IF NOT EXISTS PUBLIC
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: false

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: Asia/Seoul
          batch_size: 20
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: create-drop
        packages_to_scan: com.sleekydz86.kopanda.infrastructure.persistence.entities
    defer-datasource-initialization: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: Asia/Seoul

  profiles:
    active: dev

logging:
  level:
    com.sleekydz86.kopanda: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.tool.schema: DEBUG

kafka:
  client:
    bootstrap-servers: localhost:9092
    default-timeout-ms: 5000
    request-timeout-ms: 3000
    metadata-max-age-ms: 300000
    reconnect-backoff-ms: 50
    retry-backoff-ms: 100
    max-block-ms: 60000
    buffer-memory: 33554432
    compression-type: none
    batch-size: 16384
    linger-ms: 0
    max-request-size: 1048576
    receive-buffer-bytes: 32768
    send-buffer-bytes: 131072
    max-in-flight-requests-per-connection: 5
    connections-max-idle-ms: 540000
    session-timeout-ms: 30000
    heartbeat-interval-ms: 3000
    max-poll-records: 500
    max-poll-interval-ms: 300000
    auto-offset-reset: earliest
    enable-auto-commit: false
    auto-commit-interval-ms: 5000
    check-crcs: true
    exclude-internal-topics: true
    isolation-level: read_uncommitted
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

  admin:
    request-timeout-ms: 5000
    default-api-timeout-ms: 5000
    operation-timeout-ms: 30000
    fetch-timeout-ms: 5000

  consumer:
    group-id: kopanda-consumer
    auto-offset-reset: earliest
    enable-auto-commit: false
    max-poll-records: 500
    max-poll-interval-ms: 300000
    session-timeout-ms: 30000
    heartbeat-interval-ms: 3000
    fetch-min-bytes: 1
    fetch-max-wait-ms: 500
    fetch-max-bytes: 52428800
    max-partition-fetch-bytes: 1048576
    check-crcs: true
    exclude-internal-topics: true
    isolation-level: read_uncommitted

  producer:
    acks: all
    retries: 2147483647
    batch-size: 16384
    linger-ms: 0
    buffer-memory: 33554432
    compression-type: none
    max-request-size: 1048576
    max-block-ms: 60000
    request-timeout-ms: 30000
    delivery-timeout-ms: 120000
    enable-idempotence: false
    max-in-flight-requests-per-connection: 5
    metadata-max-age-ms: 300000
    reconnect-backoff-ms: 50
    retry-backoff-ms: 100

app:
  connection:
    default-port: 9092
    test-timeout-ms: 5000
    max-connections: 100
    connection-pool-size: 10
    default-host: localhost


# 기존 설정에 추가
kafka:
  jmx:
    enabled: true
    port: 9999
    host: localhost
    username: null
    password: null
    ssl: false
    ssl-truststore: null
    ssl-truststore-password: null
    ssl-keystore: null
    ssl-keystore-password: null

# Prometheus 메트릭 엔드포인트 추가
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true